#ifndef USE_ALLOBJECTS
#define USE_ALLOBJECTS
//LIST OF ALL GAME OBJECT INCLUDES - YOU *WILL* CREATE CIRCULAR DEPENDENCY BY INCLUDING THIS IN A .H FILE
#include "FPSCounter.h"
#include "PlayerController.h"
#endif
